# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

env:
  DOCKER_USERNAME: sanvu
  DOCKER_PASSWORD: ${{ secrets.PASS1 }}
  IMAGE_TAG: ${{ github.sha }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}

    - name: Docker Build
      run: docker build . -t ${DOCKER_USERNAME}/test:${IMAGE_TAG}

    - name: docker push
      run: docker push ${DOCKER_USERNAME}/testpy:${IMAGE_TAG}